let car: string = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda');
console.log("Is car != 'subaru'? I predict False.");
console.log(car != 'subaru');
console.log("Is car != 'honda'? I predict True.");
console.log(car != 'honda');
console.log("Is 5 > 3? I predict True.");
console.log(5 > 3);
console.log("Is 10 < 5? I predict False.");
console.log(10 < 5);
console.log("Is 7 >= 5? I predict True.");
console.log(7 >= 5);
console.log("Is 3 <= 1? I predict False.");
console.log(3 <= 1);
console.log("Is (5 > 3) && (10 < 5)? I predict False.");
console.log((5 > 3) && (10 < 5));
console.log("Is (5 > 3) || (10 < 5)? I predict True.");
console.log((5 > 3) || (10 < 5));
console.log("Is 'apple' in ['apple', 'banana', 'cherry']? I predict True.");
console.log(['apple', 'banana', 'cherry'].includes('apple'));
console.log("Is 'grape' in ['apple', 'banana', 'cherry']? I predict False.");
console.log(['apple', 'banana', 'cherry'].includes('grape'));
